### ISSUE TITLE
The function `GetHDpiFormonitor` doesn't exist

### ISSUE THREAD

**Issue by wayneuroda** [salarcode/Salar.DpiAware#1]
Win32Api.cs imports the function `GetHDpiFormonitor` from Shcore.dll, but the function seems to be called `GetDpiForMonitor` as you can see here: https://msdn.microsoft.com/en-us/library/windows/desktop/dn280510(v=vs.85).aspx

**Comment by salarcode** [comment]
Thanks. It is fixed now.
