### ISSUE TITLE
Add EnableNonClientDpiScaling calls 

### ISSUE THREAD

**Issue by MagicAndre1981** [salarcode/Salar.DpiAware#2]
Can you add [EnableNonClientDpiScaling](https://msdn.microsoft.com/en-us/library/windows/desktop/mt748621%28v=vs.85%29.aspx) calls? This was added in 1607 Update for Win10 to [scale Titlebar](http://stackoverflow.com/q/36864894/1466046).

**Comment by salarcode** [comment]
Sure, I will look at it in my spare time.

**Comment by salarcode** [comment]
It is added in v1.2
